name: Android APK Build (Nano Bot)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || true

    - name: Download Gradle wrapper if missing
      run: |
        if [ ! -f "./gradlew" ]; then
          wget https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip gradle-8.9-bin.zip
          mv gradle-8.9 gradle
          echo "Gradle wrapper not found, installed manually."
        fi

    - name: Build Android App (APK)
      run: ./gradlew assembleDebug

    - name: Upload generated APK
      uses: actions/upload-artifact@v4
      with:
        name: VoiceEye-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
